Fix build on macOS when no ATR parser is used
pcsc_scan.c:496:38: error: use of undeclared identifier 'ATR_PARSER'
        char atr_command[sizeof(atr)+sizeof(ATR_PARSER)+2+1];
                                            ^

Fixes: https://github.com/LudovicRousseau/pcsc-tools/issues/72